version: '3.1'

services:
    redis:
        image: redis:alpine
        container_name: accelance-redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - accelance-net

    accelance:
        container_name: accelance-main
        build:
            context: .. # Build using the Dockerfile in the root directory
            dockerfile: docker/Dockerfile
        ports:
            - '${PORT}:${PORT}'
        volumes:
            # Mount local .accelance to container's default location
            - ../.accelance:/root/.accelance
        environment:
            # --- Essential Accelance Vars ---
            - PORT=${PORT:-3000}
            - DATABASE_PATH=/root/.accelance
            - SECRETKEY_PATH=/root/.accelance
            - LOG_PATH=/root/.accelance/logs
            - BLOB_STORAGE_PATH=/root/.accelance/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=accelance-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
        networks:
            - accelance-net

    accelance-worker:
        container_name: accelance-worker
        build:
            context: .. # Build context is still the root
            dockerfile: docker/worker/Dockerfile # Ensure this path is correct
        volumes:
            # Mount same local .accelance to worker
            - ../.accelance:/root/.accelance
        environment:
            # --- Essential Accelance Vars ---
            - WORKER_PORT=${WORKER_PORT:-5566} # Port for worker healthcheck
            - DATABASE_PATH=/root/.accelance
            - SECRETKEY_PATH=/root/.accelance
            - LOG_PATH=/root/.accelance/logs
            - BLOB_STORAGE_PATH=/root/.accelance/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=accelance-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
            - accelance
        networks:
            - accelance-net

volumes:
    redis_data:
        driver: local

networks:
    accelance-net:
        driver: bridge
